### PR TITLE
Increase error propagation of library functions

### LINKED ISSUE #11: Error handling
Per #10 , i'd like to call reap within another program.

Currently, I'll probably have to wrap the call point with https://doc.rust-lang.org/std/panic/fn.catch_unwind.html since there are a number of `unwrap` and `expect` and `assert` calls within the code.

We should instead return early with an appropriate error and bubble these errors up, so that we can have some certainty that the reap code will not crash the overall program.

### PR DESCRIPTION
**Pull request by dalehamel**
# What

This adds error handling to src/analysis.rs and src/parse.rs, where it was otherwise lacking it. Afaict nothing to be done in src/object.rs. Note though that I **did not bother doing main.rs** as this is not called as a library. If called as a binary, it is fine to just explode and print the backtrace as we are doing now. Closes #11 

I have done away with all calls to:

- `unwrap`
- `expect`
- `assert!`

I also did a commit to address all `cargo clippy` warnings.

# Why

So that we should be able to safely call functions without worrying about them exploding and crashing the whole process if reap is used as a library if they encounter an error. Related to #10 

# How

Wherever possible, I've used `?` to propagate the error, otherwise errors are mapped to an error type where appropriate.

Function signatures that were missing a `Result` wrapper in the return type have had them added.

# Reviewers notes

The logic should be otherwise identical. Please verify that I didn't fudge this up!

**disclaimer** I had chat GPT do a lot of the heavy lifting here, please help me double-check the bot.

Please also verify I didn't miss any other cases where we should be propagating an error rather than panicking.

### CODE REVIEW

File: src/analyze.rs [hunk 1]
```diff
@@ -36,31 +36,59 @@ pub struct Analysis {
...
+        match self {
+            AnalysisError::NodeCountMismatch => write!(f, "Node count mismatch"),
+            AnalysisError::DominatorAddrLengthExceeded => {
+                write!(f, "Dominator addr length exceeded")
+            } // Add other variants as needed
+        }
+    }
+}
+
+impl std::error::Error for AnalysisError {
```
Comment (dalehamel) [inline src/analyze.rs]: We can probably delete this boilerplate

**Comment by dalehamel** [comment]
FYI on this also @ianks I believe you are a maintainer?

File: src/parse.rs [hunk 2]
```diff
@@ -138,32 +158,44 @@ pub fn parse(
     let mut line_buffer = vec![];
 
     while let Ok(bytes_read) = reader.read_until(0x0A, &mut line_buffer) {
-        if bytes_read <= 0 {
+        if bytes_read == 0 {
```
Comment (dalehamel) [inline src/parse.rs:154]: Whoops i didn't meant to change this - bad bot! 🙅 🤖

File: src/parse.rs [hunk 3]
```diff
@@ -179,10 +211,10 @@ pub fn parse(
         }
     }
 
-    for mut obj in graph.node_weights_mut() {
+    for obj in graph.node_weights_mut() {
         if let Some(module) = instances.get(&obj.address) {
             if let Some(name) = names.get(module) {
-                obj.kind = name.to_owned();
+                name.clone_into(&mut obj.kind);
```
Comment (dalehamel) [inline src/parse.rs:210]: recommended by clippy

File: src/parse.rs [hunk 4]
```diff
@@ -179,10 +211,10 @@ pub fn parse(
         }
     }
 
-    for mut obj in graph.node_weights_mut() {
```
Comment (dalehamel) [inline src/parse.rs]: clippy and compiler both say this doesn't need mut

File: src/parse.rs (hunk 2 above)
Comment (dalehamel) [inline src/parse.rs:154]: Actually, clippy also called this out:

```
error: this comparison involving the minimum or maximum element for this type contains a case that is always true or always false
   --> src/parse.rs:161:12
    |
161 |         if bytes_read <= 0 {
    |            ^^^^^^^^^^^^^^^
    |
    = help: because `0` is the minimum value for this type, the case where the two sides are not equal never occurs, consider using `bytes_read == 0` instead
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#absurd_extreme_comparisons
    = note: `#[deny(clippy::absurd_extreme_comparisons)]` on by default
```

Including the change, per the above reasoning.

File: src/analyze.rs [hunk 5]
```diff
@@ -153,13 +173,15 @@ fn extract_dominated_subgraph(
...
     };
 
-    // Cheap sanity checks
-    assert!(reachable.len() <= graph.node_count());
-    assert!(dominator_addrs.len() <= graph.node_count());
-    assert!(dominator_addrs.len() <= dominators.len());
-    assert!(dominator_addrs.len() <= reachable.len());
-    assert_eq!(dominated.node_count() + rest.len(), reachable.len());
-    assert!(dominated.node_count() <= dominator_addrs.len() + 1);
+    if reachable.len() > graph.node_count()
```
Comment (bmansoob) [inline src/analyze.rs:176]: I wonder if some of these checks should be moved up, that is return early if error.

**Review by bmansoob — APPROVED** [review]

File: src/analyze.rs (hunk 5 above)
Comment (dalehamel) [reply src/analyze.rs:176]: i think you're right that many of them could be, except for the last two, "dominated", as that is computed on the statement before this.

We can do return early in a future PR
